CC = gcc
CFLAGS = -Wall -g -std=c99

BIN = ./bin/
SRC = ./src/

program:
	$(CC) $(CFLAGS) $(SRC)main.c $(SRC)bookMain.c $(SRC)boardgameMain.c $(SRC)storeMain.c -Iinclude -o $(BIN)program

cls:
	clear

